id: 98608ffa-7fb2-4fb0-9add-fb9a8debbab8
description: Example description
variables:
  project_name:
    prompt: Enter a name for your project
  secret_key:
    prompt: The output of this command: python -c "import os; print repr(os.urandom(30))"
  allauth:
    prompt: Do you want to use django-allauth?
    type: boolean
