id: 98608ffa-7fb2-4fb0-9add-fb9a8debbab8
description: "A starter Django 1.5 project with South, and optionally django-allauth, raven and django-compressor."
variables:
  project_name:
    prompt: Enter a name for your project
  secret_key:
    prompt: "The output of this command: python -c \"import random; print repr(''.join(chr(random.randint(32,126)) for x in xrange(60)))\""
  allauth:
    prompt: Do you want to use django-allauth?
    type: boolean
